### ISSUE TITLE
Fix codecov 0% issue by using pytest-cov 

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#30]
@Tieqiong 

Can we try to implement the below change? 

---

We shall use `pytest-cov` instead of using coverage to run pytest. The previous codecov 0% error occurred because the tests folder has been moved to the top directory level and coverage isn't able to import diffpy.<package-name> due to the namespace.

So the GH actions can be modified 

from:

```
        run: |
          coverage run -m pytest -vv -s
          coverage report -m
          codecov
```

to:

```
        run: |
          pytest --cov
          coverage report -m
          codecov
```

Reference:
- https://github.com/diffpy/diffpy.snmf/pull/86

Two more things to confirm with you:

I will also update `.coveragerc` to remove the `source` section.

Reference:
- https://github.com/diffpy/diffpy.snmf/pull/86/files

I will include `pytest-cov` in the `test.txt` dependency list.

**Comment by Tieqiong** [comment]
@bobleesj yes please make a PR in `release-script`

**Comment by bobleesj** [comment]
Got it. Once the PR is merged above, I will test whether it codecov % works using `diffpy.utils` and `diffpy.snmf`.

And then I will modify `test.txt` and `.coveragerc` in the overall cookiecutter.

**Comment by bobleesj** [comment]
Closes with https://github.com/Billingegroup/cookiecutter/pull/155
