### ISSUE TITLE
News CI does not fail when there are existing news .rst files

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#39]
Expected behavior:

- The CI should write a comment and fail when there is no news item provided.

Bug:

- When there are existing news items in the `main` branch, the CI warns but does not fail.

Reference:
- https://github.com/diffpy/diffpy.snmf/pull/87 (bug found here)
- https://github.com/bobleesj/diffpy.snmf/tree/central-ci/news

**Comment by sbillinge** [comment]
nice catch
