### ISSUE TITLE
Use GitHub CI to build wheels,  (pre)-release on PyPI/conda-forge

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#52]
As discussed with @sbillinge 

When a tag is pushed, we can use GitHub CI to automate (pre)-release in a single workflow.

Actions steps:

- build wheels for each OS (macOS arm64/intel, ubuntu, windows) and Python versions
- distribute wheels and `sdist` to PyPI 
- create a PR on conda-forge feedstock for review
- compile/generate release news

I had a preliminary test result that the CI can build a wheel for macOS (arm64) for `diffpy.pdffit2`.

<img width="737" alt="Screenshot 2024-09-27 at 9 36 57 PM" src="https://github.com/user-attachments/assets/2943c442-4ac7-4192-bf32-e3b0e3710ed4">

**Comment by sbillinge** [comment]
This seems very promising, especially now we have the GH workflows under a central repo control. 

Can we have a quick discussion with @Sparks29032  and @Tieqiong and make sure there are no downsides that concern us, as this would be a major shift in how we do things, but right now I don't see any major downsides and plenty of upsides. Thanks @bobleesj !

**Comment by sbillinge** [comment]
@bobleesj please can you work to arrange that meeting early next week?

**Comment by bobleesj** [comment]
> @bobleesj please can you work to arrange that meeting early next week?

Yes will finalize during today's lunch

**Comment by bobleesj** [comment]
@sbillinge Closing, we now build wheels with GitHub CI
