### ISSUE TITLE
Organize/remove older scripts for better maintenance

### ISSUE THREAD

**Issue by bobleesj** [Billingegroup/release-scripts#99]
![Screenshot 2024-12-05 at 3 03 46 PM](https://github.com/user-attachments/assets/42043460-78a3-45c3-9951-02ee4bde2cec)

@sbillinge 

We have `.txt`, `.sh`, and `.py` that we may no longer need since many of the functions have been replaced by GitHub CI. 

Can we separate our older scripts into a folder called `archive` or delete some of them?

**Comment by sbillinge** [comment]
let's tag the repo before deleting `git tag 2024-12-before-cleanup`
